name: example
description: A example project for dbstyleguidechecker style checker.
version: 1.0.0
author: darelbitsy <bitsydarel@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  flutter_code_style: ^1.6.2
  test: ^1.8.0