name: dbstyleguidechecker
description: A tool that help you verify a project agains code style guide and automatize pull request review.
version: 1.0.3
homepage: https://github.com/bitsydarel/dbstyleguidechecker
author: darelbitsy <bitsydarel@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  path: ^1.6.4
  args: ^1.5.2
  meta: ^1.1.7
  http: ^0.12.0+2
  io: ^0.3.3

dev_dependencies:
  flutter_code_style: ^1.6.3
  test: ^1.8.0

executables:
  dbstyleguidechecker: