name: dbstyleguidechecker
description: A tool that help you verify a project agains code style guide and automatize pull request review.
version: 3.0.0-nullsafety.0
homepage: https://github.com/bitsydarel/dbstyleguidechecker
repository: https://github.com/bitsydarel/dbstyleguidechecker
issue_tracker: https://github.com/bitsydarel/dbstyleguidechecker/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  http: ^0.13.0
  io: ^1.0.0
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  flutter_code_style: ^2.0.2
  test: ^1.15.7

executables:
  dbstyleguidechecker: